--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/6/27 13:15:32
-- Server version: 5.5.52
-- Client version: 4.1
--

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for table demo_room
--
DROP TABLE IF EXISTS demo_room;
CREATE TABLE demo_room (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  room_id BIGINT(20) UNSIGNED NOT NULL COMMENT '聊天室房间号',
  creator VARCHAR(64) NOT NULL COMMENT '房主账号',
  name VARCHAR(128) NOT NULL COMMENT '房间名称',
  is_public BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否为公共聊天室，0-不是；1-是',
  ext VARCHAR(4096) DEFAULT NULL COMMENT 'json格式的聊天室扩展字段',
  cid VARCHAR(64) DEFAULT NULL COMMENT '直播频道ID',
  av_type TINYINT(2) UNSIGNED DEFAULT NULL COMMENT '直播音视频类型，1-音频直播，2-视频直播',
  orientation TINYINT(2) UNSIGNED DEFAULT NULL COMMENT '直播屏幕方向，1-竖屏，2-横屏',
  push_url VARCHAR(255) DEFAULT NULL COMMENT '推流地址',
  rtmp_pull_url VARCHAR(255) DEFAULT NULL COMMENT 'rtmp拉流地址',
  hls_pull_url VARCHAR(255) DEFAULT NULL COMMENT 'hls拉流地址',
  http_pull_url VARCHAR(255) DEFAULT NULL COMMENT 'http拉流地址',
  created_at TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:00' COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  INDEX idx_owner (creator),
  INDEX idx_roomid (room_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '聊天室直播房间信息表';

--
-- Definition for table demo_seq
--
DROP TABLE IF EXISTS demo_seq;
CREATE TABLE demo_seq (
  id BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 100000
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '生成递增序列号表';

--
-- Definition for table demo_user
--
DROP TABLE IF EXISTS demo_user;
CREATE TABLE demo_user (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  accid VARCHAR(64) NOT NULL COMMENT '用户账号',
  nickname VARCHAR(64) NOT NULL COMMENT '用户昵称',
  password VARCHAR(64) NOT NULL COMMENT '密码',
  phone VARCHAR(64) NOT NULL COMMENT '电话',
  im_token VARCHAR(64) DEFAULT NULL COMMENT 'im token',
  vod_token VARCHAR(64) DEFAULT NULL COMMENT '点播token',
  created_at TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:00' COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  INDEX index_phone (phone),
  INDEX index_username (accid)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户信息表';

--
-- Definition for table demo_video
--
DROP TABLE IF EXISTS demo_video;
CREATE TABLE demo_video (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  vid BIGINT(20) NOT NULL COMMENT '视频id',
  name VARCHAR(256) NOT NULL COMMENT '视频文件名',
  owner VARCHAR(64) NOT NULL COMMENT '上传用户',
  type TINYINT(2) NOT NULL DEFAULT 0 COMMENT '视频类型，0-普通视频，1-短视频',
  created_at TIMESTAMP NOT NULL DEFAULT '2017-01-01 00:00:00' COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  INDEX idx_owner (owner),
  INDEX idx_vid (vid)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'demo视频信息表';
